namespace Fhir.QueryBuilder.Localization;

/// <summary>Query Builder UI 靜態字串（五語系；Blazor／Avalonia 等共用）。</summary>
public sealed record QueryBuilderUiStrings(
    string Active,
    string Add,
    string AddElements,
    string AddSort,
    string AddTypedClauseToDraft,
    string AppTitleShort,
    string BearerTokenOptional,
    string BuildComposedUrl,
    string Cancel,
    string CapabilitySearchParams,
    string CardDraftQueryLines,
    string CardQuery,
    string CardResult,
    string CanonicalUrlPlaceholder,
    string ChainParameters,
    string Clear,
    string ClearAdvanced,
    string ClearAll,
    string ClearElements,
    string ClearSmartSession,
    string ClearSort,
    string ClearUrl,
    string ClientId,
    string Code,
    string CodeOnly,
    string CodeWithSystem,
    string ComponentValue,
    string ComponentsCommaPlaceholder,
    string Composite,
    string CompositeCsvHint,
    string CompositeCsvPlaceholder,
    string CompositeLocalBlocks,
    string CompositeMetadataFromServer,
    string CompositeParameters,
    string Connect,
    string ContactNameLine,
    string CopyrightLineFormat,
    string Copy,
    string CopyTokenUrl,
    string Date,
    string DecimalNumber,
    string Detected,
    string EditorUnsupported,
    string ElementsSortSection,
    string ElementsList,
    string EmitEveryListedPath,
    string ExecuteQuery,
    string FilterExpressionPlaceholder,
    string FilterExpressions,
    string FhirBaseUrlPlaceholder,
    string FhirDeclaration,
    string FhirFilterPlaceholder,
    string FooterAltItriLogo,
    string FullQueryUrlPlaceholder,
    string JsonPlaceholder,
    string JwtClientCredentials,
    string Language,
    string LogicalId,
    string LogicalIdTypeSlash,
    string MaxResultsInBundle,
    string Modifier,
    string ModifierLabel,
    string ModifyingSectionTitle,
    string NoDraftLines,
    string Number,
    string OpenAuthorizeUrl,
    string OpenTokenUrl,
    string OrCodedQuantity,
    string ParameterNamePlaceholder,
    string PaginationCount,
    string PathPlaceholderChain,
    string PrefixOption,
    string PrivateKeyPemPlaceholder,
    string Quantity,
    string RefreshAccessToken,
    string Reference,
    string RemoveSelected,
    string ResetThisPage,
    string ResourceType,
    string ResourceTypePh,
    string ResultControl,
    string ResultElementsCsvPlaceholder,
    string ResultViewMessage,
    string ResultViewTree,
    string Save,
    string ScopesPlaceholder,
    string SelectedLabel,
    string SelectedNone,
    string SmartLoginPkce,
    string SmartOnFhir,
    string SmartPatientContextFormat,
    string SortList,
    string SortPrefixMinus,
    string Special,
    string SpecialValueHint,
    string String,
    string SystemLabel,
    string TabAdvanced,
    string TabInclude,
    string TabModifyingResults,
    string TabRevInclude,
    string TabSearchParameters,
    string Token,
    string TreeViewError,
    string UnsetOption,
    string Uri,
    string UriValue,
    string Value,
    string ValueNumberPlaceholder,
    string BearerTokenAvaloniaWatermark,
    string Exit,
    string FullQueryUrlBuiltBelow,
    string ResourceTypeAutocompleteWatermark,
    string SmartClientIdWatermark,
    string SmartPrivateKeyPemWatermark,
    string SmartScopesWatermark,
    string TypedBuilderSection,
    string Version)
{
    public static QueryBuilderUiStrings For(string cultureCode) =>
        QueryBuilderUiCultureCodes.Normalize(cultureCode) switch
        {
            QueryBuilderUiCultureCodes.ZhCn => ZhCn,
            QueryBuilderUiCultureCodes.En => En,
            QueryBuilderUiCultureCodes.Ja => Ja,
            QueryBuilderUiCultureCodes.Ko => Ko,
            _ => ZhTw,
        };

    private static readonly QueryBuilderUiStrings ZhTw = new(
        Active: "作用",
        Add: "加入",
        AddElements: "加入 Elements",
        AddSort: "加入 Sort",
        AddTypedClauseToDraft: "加入型別子句至草稿",
        AppTitleShort: "FHIR Query Builder",
        BearerTokenOptional: "Bearer access token（選填）",
        BuildComposedUrl: "組合完整 URL",
        Cancel: "取消",
        CapabilitySearchParams: "Capability 搜尋參數",
        CardDraftQueryLines: "草稿查詢行",
        CardQuery: "查詢",
        CardResult: "結果",
        CanonicalUrlPlaceholder: "Canonical URL",
        ChainParameters: "鏈結參數（chain）",
        Clear: "清除",
        ClearAdvanced: "清除進階條件",
        ClearAll: "全部清除",
        ClearElements: "清空 Elements",
        ClearSmartSession: "清除 SMART session",
        ClearSort: "清空 Sort",
        ClearUrl: "清除 URL",
        ClientId: "Client ID",
        Code: "代碼",
        CodeOnly: "僅代碼",
        CodeWithSystem: "代碼（含 system）",
        ComponentValue: "元件值",
        ComponentsCommaPlaceholder: "元件（逗號分隔）",
        Composite: "Composite",
        CompositeCsvHint: "至少兩個以逗號分隔的元件；依 FHIR composite 搜尋以 $ 連接。",
        CompositeCsvPlaceholder: "component1, component2, …",
        CompositeLocalBlocks: "使用本機元件區塊（metadata 缺失時依參數名稱推斷型別，為最佳努力）。每個區塊為一個元件；加入草稿時以 $ 連接。",
        CompositeMetadataFromServer: "已自伺服器 SearchParameter.component 載入元件（TD-1）。",
        CompositeParameters: "複合參數（composite）",
        Connect: "連線",
        ContactNameLine: "聯絡人：范士展（Fan Shih-Chan）",
        CopyrightLineFormat: "© {0} 工業技術研究院（ITRI）。版權所有。",
        Copy: "複製",
        CopyTokenUrl: "複製 token URL",
        Date: "Date",
        DecimalNumber: "小數數值",
        Detected: "偵測",
        EditorUnsupported: "此參數型別尚無型別化編輯器 — 請使用草稿行或原始 FHIR 語法。",
        ElementsSortSection: "_elements／_sort",
        ElementsList: "Elements 列表",
        EmitEveryListedPath: "輸出清單中所有路徑",
        ExecuteQuery: "執行查詢",
        FilterExpressionPlaceholder: "FHIR filter 運算式",
        FilterExpressions: "_filter 運算式",
        FhirBaseUrlPlaceholder: "FHIR base URL",
        FhirDeclaration: "FHIR 宣告",
        FhirFilterPlaceholder: "FHIR filter 運算式",
        FooterAltItriLogo: "工業技術研究院 Industrial Technology Research Institute",
        FullQueryUrlPlaceholder: "完整查詢 URL",
        JsonPlaceholder: "JSON",
        JwtClientCredentials: "JWT client_credentials",
        Language: "語言",
        LogicalId: "logical id",
        LogicalIdTypeSlash: "logical id（type/id）",
        MaxResultsInBundle: "Bundle 內最大筆數",
        Modifier: "修飾詞",
        ModifierLabel: "修飾詞標籤",
        ModifyingSectionTitle: "結果修飾參數",
        NoDraftLines: "（尚無草稿行）",
        Number: "Number",
        OpenAuthorizeUrl: "開啟 authorize URL",
        OpenTokenUrl: "開啟 token URL",
        OrCodedQuantity: "或以 coding 表示之數量：",
        ParameterNamePlaceholder: "參數名稱",
        PaginationCount: "分頁筆數",
        PathPlaceholderChain: "路徑（例：patient.name）",
        PrefixOption: "前綴",
        PrivateKeyPemPlaceholder: "機密客戶端 PEM",
        Quantity: "Quantity",
        RefreshAccessToken: "重新整理 access token",
        Reference: "參照（Reference）",
        RemoveSelected: "移除選取",
        ResetThisPage: "重設本頁",
        ResourceType: "資源類型",
        ResourceTypePh: "ResourceType",
        ResultControl: "結果控制（_count、_offset、_total、_summary、_elements）",
        ResultElementsCsvPlaceholder: "以逗號分隔的元素名稱",
        ResultViewMessage: "文字檢視",
        ResultViewTree: "樹狀檢視",
        Save: "儲存…",
        ScopesPlaceholder: "Scopes",
        SelectedLabel: "已選：",
        SelectedNone: "（無）",
        SmartLoginPkce: "SMART 登入（瀏覽器 PKCE）",
        SmartOnFhir: "SMART on FHIR",
        SmartPatientContextFormat: "SMART patient 情境：{0}",
        SortList: "Sort 列表",
        SortPrefixMinus: "Sort 前綴「-」",
        Special: "Special",
        SpecialValueHint: "值格式依此 SearchParameter 而定；請見上方說明或伺服器文件。",
        String: "String",
        SystemLabel: "system",
        TabAdvanced: "進階",
        TabInclude: "_include",
        TabModifyingResults: "結果修飾",
        TabRevInclude: "_revinclude",
        TabSearchParameters: "搜尋參數",
        Token: "Token",
        TreeViewError: "樹狀顯示發生錯誤（JSON 可能過大或過深）。請改用「文字檢視」檢視原始文字。",
        UnsetOption: "（未設定）",
        Uri: "Uri",
        UriValue: "URI 值",
        Value: "值",
        ValueNumberPlaceholder: "數值",
        BearerTokenAvaloniaWatermark: "Bearer access token（選填，Execute query 時附加 Authorization）",
        Exit: "結束",
        FullQueryUrlBuiltBelow: "完整查詢 URL（下方組建）",
        ResourceTypeAutocompleteWatermark: "選擇或輸入類型",
        SmartClientIdWatermark: "在 IdP 註冊的 client_id",
        SmartPrivateKeyPemWatermark: "機密客戶端：RSA/EC 私鑰 PEM（選填；亦可改 appsettings ConfidentialPrivateKeyPem）",
        SmartScopesWatermark: "Scopes（例：launch/patient patient/*.read openid fhirUser offline_access）",
        TypedBuilderSection: "型別化編輯",
        Version: "版本");

    private static readonly QueryBuilderUiStrings ZhCn = ZhTw with
    {
        Active = "生效",
        Add = "添加",
        AddElements = "添加 Elements",
        AddSort = "添加 Sort",
        AddTypedClauseToDraft = "将类型化子句添加到草稿",
        BearerTokenOptional = "Bearer access token（可选）",
        BuildComposedUrl = "组合完整 URL",
        Cancel = "取消",
        CapabilitySearchParams = "Capability 搜索参数",
        CardDraftQueryLines = "草稿查询行",
        CardQuery = "查询",
        CardResult = "结果",
        CanonicalUrlPlaceholder = "Canonical URL",
        ChainParameters = "链式参数（chain）",
        Clear = "清除",
        ClearAdvanced = "清除高级条件",
        ClearAll = "全部清除",
        ClearElements = "清空 Elements",
        ClearSmartSession = "清除 SMART 会话",
        ClearSort = "清空 Sort",
        ClearUrl = "清除 URL",
        Code = "代码",
        CodeOnly = "仅代码",
        CodeWithSystem = "代码（含 system）",
        ComponentValue = "组件值",
        ComponentsCommaPlaceholder = "组件（逗号分隔）",
        CompositeCsvHint = "至少两个逗号分隔的组件；按 FHIR composite 搜索以 $ 连接。",
        CompositeLocalBlocks = "使用本地组件块（缺少 metadata 时按参数名推断类型，尽力而为）。每个块为一个组件；添加到草稿时以 $ 连接。",
        CompositeMetadataFromServer = "已从服务器 SearchParameter.component 加载组件（TD-1）。",
        CompositeParameters = "复合参数（composite）",
        ContactNameLine = "联系人：范士展（Fan Shih-Chan）",
        CopyrightLineFormat = "© {0} 工业技术研究院（ITRI）。版权所有。",
        Copy = "复制",
        CopyTokenUrl = "复制 token URL",
        Detected = "检测",
        EditorUnsupported = "此参数类型尚无类型化编辑器 — 请使用草稿行或原始 FHIR 语法。",
        ElementsList = "元素列表",
        ElementsSortSection = "_elements／_sort",
        EmitEveryListedPath = "输出列表中的所有路径",
        ExecuteQuery = "执行查询",
        FilterExpressionPlaceholder = "FHIR filter 表达式",
        FilterExpressions = "_filter 表达式",
        FhirDeclaration = "FHIR 声明",
        FooterAltItriLogo = "工业技术研究院 Industrial Technology Research Institute",
        FullQueryUrlPlaceholder = "完整查询 URL",
        Language = "语言",
        MaxResultsInBundle = "Bundle 内最大条数",
        ModifyingSectionTitle = "结果修饰参数",
        NoDraftLines = "（尚无草稿行）",
        OpenAuthorizeUrl = "打开 authorize URL",
        OpenTokenUrl = "打开 token URL",
        OrCodedQuantity = "或以 coding 表示的数量：",
        ParameterNamePlaceholder = "参数名称",
        PaginationCount = "分页条数",
        PathPlaceholderChain = "路径（例：patient.name）",
        PrivateKeyPemPlaceholder = "机密客户端 PEM",
        Quantity = "Quantity",
        RefreshAccessToken = "刷新 access token",
        Reference = "Reference",
        RemoveSelected = "移除所选",
        ResetThisPage = "重置本页",
        ResourceType = "资源类型",
        ResultControl = "结果控制（_count、_offset、_total、_summary、_elements）",
        ResultElementsCsvPlaceholder = "逗号分隔的元素名称",
        ResultViewMessage = "文本视图",
        ResultViewTree = "树状视图",
        Save = "保存…",
        SelectedLabel = "已选：",
        SmartLoginPkce = "SMART 登录（浏览器 PKCE）",
        SmartPatientContextFormat = "SMART patient 上下文：{0}",
        SortList = "Sort 列表",
        SortPrefixMinus = "Sort 前缀「-」",
        SpecialValueHint = "值格式取决于此 SearchParameter；请见上方说明或服务器文档。",
        SystemLabel = "system",
        TabAdvanced = "高级",
        TabModifyingResults = "结果修饰",
        TabSearchParameters = "搜索参数",
        TreeViewError = "树状显示出错（JSON 可能过大或过深）。请改用「文本视图」查看原始文本。",
        UnsetOption = "（未设置）",
        BearerTokenAvaloniaWatermark = "Bearer access token（可选，执行查询时附加 Authorization）",
        Exit = "退出",
        FullQueryUrlBuiltBelow = "完整查询 URL（下方构建）",
        ResourceTypeAutocompleteWatermark = "选择或输入类型",
        SmartClientIdWatermark = "在 IdP 注册的 client_id",
        SmartPrivateKeyPemWatermark = "机密客户端：RSA/EC 私钥 PEM（可选；也可改 appsettings ConfidentialPrivateKeyPem）",
        SmartScopesWatermark = "Scopes（示例：launch/patient patient/*.read openid fhirUser offline_access）",
        TypedBuilderSection = "类型化编辑",
        Connect = "连接",
    };

    private static readonly QueryBuilderUiStrings En = new(
        Active: "Active",
        Add: "Add",
        AddElements: "Add element",
        AddSort: "Add sort",
        AddTypedClauseToDraft: "Add typed clause to draft",
        AppTitleShort: "FHIR Query Builder",
        BearerTokenOptional: "Bearer access token (optional)",
        BuildComposedUrl: "Build composed URL",
        Cancel: "Cancel",
        CapabilitySearchParams: "Capability search params",
        CardDraftQueryLines: "Draft query lines",
        CardQuery: "Query",
        CardResult: "Result",
        CanonicalUrlPlaceholder: "canonical URL",
        ChainParameters: "Chain parameters",
        Clear: "Clear",
        ClearAdvanced: "Clear advanced",
        ClearAll: "Clear all",
        ClearElements: "Clear elements",
        ClearSmartSession: "Clear SMART session",
        ClearSort: "Clear sort",
        ClearUrl: "Clear URL",
        ClientId: "Client ID",
        Code: "code",
        CodeOnly: "code only",
        CodeWithSystem: "code (with system)",
        ComponentValue: "component value",
        ComponentsCommaPlaceholder: "components (comma-separated)",
        Composite: "Composite",
        CompositeCsvHint: "At least two comma-separated components; joined with $ per FHIR composite search.",
        CompositeCsvPlaceholder: "component1, component2, …",
        CompositeLocalBlocks: "Using local component blocks (best-effort types from the parameter name when metadata is missing). Each block is one component; joined with $ when adding to draft.",
        CompositeMetadataFromServer: "Parts loaded from server SearchParameter.component (TD-1).",
        CompositeParameters: "Composite parameters",
        Connect: "Connect",
        ContactNameLine: "Contact: Fan Shih-Chan",
        CopyrightLineFormat: "© {0} Industrial Technology Research Institute (ITRI). All rights reserved.",
        Copy: "Copy",
        CopyTokenUrl: "Copy token URL",
        Date: "Date",
        DecimalNumber: "decimal number",
        Detected: "Detected",
        EditorUnsupported: "This parameter type has no typed builder yet — use Draft lines or raw FHIR syntax.",
        ElementsSortSection: "_elements / _sort",
        ElementsList: "Elements list",
        EmitEveryListedPath: "Emit every listed path",
        ExecuteQuery: "Execute query",
        FilterExpressionPlaceholder: "FHIR filter expression",
        FilterExpressions: "_filter expressions",
        FhirBaseUrlPlaceholder: "FHIR base URL",
        FhirDeclaration: "FHIR declaration",
        FhirFilterPlaceholder: "FHIR filter expression",
        FooterAltItriLogo: "Industrial Technology Research Institute (ITRI)",
        FullQueryUrlPlaceholder: "Full query URL",
        JsonPlaceholder: "JSON",
        JwtClientCredentials: "JWT client_credentials",
        Language: "Language",
        LogicalId: "logical id",
        LogicalIdTypeSlash: "logical id (type/id)",
        MaxResultsInBundle: "Max entries in Bundle",
        Modifier: "modifier",
        ModifierLabel: "modifier label",
        ModifyingSectionTitle: "Result modifying parameters",
        NoDraftLines: "(No draft lines yet)",
        Number: "Number",
        OpenAuthorizeUrl: "Open authorize URL",
        OpenTokenUrl: "Open token URL",
        OrCodedQuantity: "Or coded quantity:",
        ParameterNamePlaceholder: "parameter name",
        PaginationCount: "Page size",
        PathPlaceholderChain: "path (e.g. patient.name)",
        PrefixOption: "prefix",
        PrivateKeyPemPlaceholder: "Confidential client PEM",
        Quantity: "Quantity",
        RefreshAccessToken: "Refresh access token",
        Reference: "Reference",
        RemoveSelected: "Remove selected",
        ResetThisPage: "Reset this page",
        ResourceType: "Resource type",
        ResourceTypePh: "ResourceType",
        ResultControl: "Result control (_count, _offset, _total, _summary, _elements)",
        ResultElementsCsvPlaceholder: "comma-separated element names",
        ResultViewMessage: "Message view",
        ResultViewTree: "Tree view",
        Save: "Save…",
        ScopesPlaceholder: "Scopes",
        SelectedLabel: "Selected:",
        SelectedNone: "(none)",
        SmartLoginPkce: "SMART login (browser PKCE)",
        SmartOnFhir: "SMART on FHIR",
        SmartPatientContextFormat: "SMART patient context: {0}",
        SortList: "Sort list",
        SortPrefixMinus: "Sort prefix \"-\"",
        Special: "Special",
        SpecialValueHint: "Value format depends on this SearchParameter; see documentation above or server docs.",
        String: "String",
        SystemLabel: "system",
        TabAdvanced: "Advanced",
        TabInclude: "_include",
        TabModifyingResults: "Modifying results",
        TabRevInclude: "_revinclude",
        TabSearchParameters: "Search parameters",
        Token: "Token",
        TreeViewError: "Tree view failed (JSON may be too large or deep). Use Message view for raw text.",
        UnsetOption: "(unset)",
        Uri: "Uri",
        UriValue: "uri value",
        Value: "value",
        ValueNumberPlaceholder: "number",
        BearerTokenAvaloniaWatermark: "Bearer access token (optional; sent as Authorization on Execute query)",
        Exit: "Exit",
        FullQueryUrlBuiltBelow: "Full query URL (built below)",
        ResourceTypeAutocompleteWatermark: "Select or type a resource type",
        SmartClientIdWatermark: "client_id registered at the IdP",
        SmartPrivateKeyPemWatermark: "Confidential client RSA/EC private key PEM (optional; or set ConfidentialPrivateKeyPem in appsettings)",
        SmartScopesWatermark: "Scopes (e.g. launch/patient patient/*.read openid fhirUser offline_access)",
        TypedBuilderSection: "Typed builder",
        Version: "version");

    private static readonly QueryBuilderUiStrings Ja = new(
        Active: "適用",
        Add: "追加",
        AddElements: "Elements を追加",
        AddSort: "Sort を追加",
        AddTypedClauseToDraft: "型付き句をドラフトに追加",
        AppTitleShort: "FHIR Query Builder",
        BearerTokenOptional: "Bearer access token（任意）",
        BuildComposedUrl: "合成 URL を構築",
        Cancel: "キャンセル",
        CapabilitySearchParams: "Capability 検索パラメータ",
        CardDraftQueryLines: "ドラフト行",
        CardQuery: "クエリ",
        CardResult: "結果",
        CanonicalUrlPlaceholder: "Canonical URL",
        ChainParameters: "チェーン検索パラメータ",
        Clear: "クリア",
        ClearAdvanced: "詳細条件をクリア",
        ClearAll: "すべてクリア",
        ClearElements: "Elements をクリア",
        ClearSmartSession: "SMART セッションをクリア",
        ClearSort: "Sort をクリア",
        ClearUrl: "URL をクリア",
        ClientId: "Client ID",
        Code: "コード",
        CodeOnly: "コードのみ",
        CodeWithSystem: "コード（system 付き）",
        ComponentValue: "コンポーネント値",
        ComponentsCommaPlaceholder: "コンポーネント（カンマ区切り）",
        Composite: "Composite",
        CompositeCsvHint: "少なくとも 2 つのカンマ区切りコンポーネント。FHIR composite 検索では $ で結合します。",
        CompositeCsvPlaceholder: "component1, component2, …",
        CompositeLocalBlocks: "ローカルコンポーネントブロックを使用（メタデータがない場合はパラメータ名から型を推定）。各ブロックは 1 コンポーネント。ドラフト追加時は $ で結合。",
        CompositeMetadataFromServer: "サーバーの SearchParameter.component から読み込み済み（TD-1）。",
        CompositeParameters: "複合パラメータ",
        Connect: "接続",
        ContactNameLine: "連絡先：Fan Shih-Chan（范士展）",
        CopyrightLineFormat: "© {0} 工業技術研究院（ITRI）。無断複写・転載を禁じます。",
        Copy: "コピー",
        CopyTokenUrl: "token URL をコピー",
        Date: "Date",
        DecimalNumber: "小数",
        Detected: "検出",
        EditorUnsupported: "このパラメータ型には型付きビルダーがありません。ドラフト行または生の FHIR 構文を使用してください。",
        ElementsSortSection: "_elements／_sort",
        ElementsList: "Elements 一覧",
        EmitEveryListedPath: "一覧のすべてのパスを出力",
        ExecuteQuery: "クエリ実行",
        FilterExpressionPlaceholder: "FHIR filter 式",
        FilterExpressions: "_filter 式",
        FhirBaseUrlPlaceholder: "FHIR base URL",
        FhirDeclaration: "FHIR 宣言",
        FhirFilterPlaceholder: "FHIR filter 式",
        FooterAltItriLogo: "工業技術研究院（ITRI）",
        FullQueryUrlPlaceholder: "完全なクエリ URL",
        JsonPlaceholder: "JSON",
        JwtClientCredentials: "JWT client_credentials",
        Language: "言語",
        LogicalId: "logical id",
        LogicalIdTypeSlash: "logical id（type/id）",
        MaxResultsInBundle: "Bundle 内の最大件数",
        Modifier: "修飾子",
        ModifierLabel: "修飾子ラベル",
        ModifyingSectionTitle: "結果修飾パラメータ",
        NoDraftLines: "（ドラフト行はまだありません）",
        Number: "Number",
        OpenAuthorizeUrl: "authorize URL を開く",
        OpenTokenUrl: "token URL を開く",
        OrCodedQuantity: "または coding による数量：",
        ParameterNamePlaceholder: "パラメータ名",
        PaginationCount: "ページサイズ",
        PathPlaceholderChain: "パス（例：patient.name）",
        PrefixOption: "接頭辞",
        PrivateKeyPemPlaceholder: "機密クライアント PEM",
        Quantity: "Quantity",
        RefreshAccessToken: "access token を更新",
        Reference: "Reference",
        RemoveSelected: "選択を削除",
        ResetThisPage: "このページをリセット",
        ResourceType: "リソース種別",
        ResourceTypePh: "ResourceType",
        ResultControl: "結果制御（_count、_offset、_total、_summary、_elements）",
        ResultElementsCsvPlaceholder: "カンマ区切りの要素名",
        ResultViewMessage: "メッセージ表示",
        ResultViewTree: "ツリー表示",
        Save: "保存…",
        ScopesPlaceholder: "Scopes",
        SelectedLabel: "選択：",
        SelectedNone: "（なし）",
        SmartLoginPkce: "SMART ログイン（ブラウザ PKCE）",
        SmartOnFhir: "SMART on FHIR",
        SmartPatientContextFormat: "SMART patient コンテキスト：{0}",
        SortList: "Sort 一覧",
        SortPrefixMinus: "Sort 接頭辞「-」",
        Special: "Special",
        SpecialValueHint: "値の形式はこの SearchParameter に依存します。上の説明またはサーバー資料を参照してください。",
        String: "String",
        SystemLabel: "system",
        TabAdvanced: "詳細",
        TabInclude: "_include",
        TabModifyingResults: "結果修飾",
        TabRevInclude: "_revinclude",
        TabSearchParameters: "検索パラメータ",
        Token: "Token",
        TreeViewError: "ツリー表示でエラーが発生しました（JSON が大きすぎるか深すぎる可能性）。「メッセージ表示」で原文を確認してください。",
        UnsetOption: "（未設定）",
        Uri: "Uri",
        UriValue: "URI 値",
        Value: "値",
        ValueNumberPlaceholder: "数値",
        BearerTokenAvaloniaWatermark: "Bearer access token（任意。Execute query で Authorization に付与）",
        Exit: "終了",
        FullQueryUrlBuiltBelow: "完全なクエリ URL（下で構築）",
        ResourceTypeAutocompleteWatermark: "リソース種別を選択または入力",
        SmartClientIdWatermark: "IdP に登録した client_id",
        SmartPrivateKeyPemWatermark: "機密クライアント RSA/EC 秘密鍵 PEM（任意。appsettings の ConfidentialPrivateKeyPem でも可）",
        SmartScopesWatermark: "Scopes（例：launch/patient patient/*.read openid fhirUser offline_access）",
        TypedBuilderSection: "型付きビルダー",
        Version: "バージョン");

    private static readonly QueryBuilderUiStrings Ko = new(
        Active: "적용",
        Add: "추가",
        AddElements: "Elements 추가",
        AddSort: "Sort 추가",
        AddTypedClauseToDraft: "형식화 절을 초안에 추가",
        AppTitleShort: "FHIR Query Builder",
        BearerTokenOptional: "Bearer access token(선택)",
        BuildComposedUrl: "조합 URL 만들기",
        Cancel: "취소",
        CapabilitySearchParams: "Capability 검색 매개변수",
        CardDraftQueryLines: "초안 쿼리 줄",
        CardQuery: "쿼리",
        CardResult: "결과",
        CanonicalUrlPlaceholder: "canonical URL",
        ChainParameters: "체인 매개변수",
        Clear: "지우기",
        ClearAdvanced: "고급 조건 지우기",
        ClearAll: "모두 지우기",
        ClearElements: "Elements 비우기",
        ClearSmartSession: "SMART 세션 지우기",
        ClearSort: "Sort 비우기",
        ClearUrl: "URL 지우기",
        ClientId: "Client ID",
        Code: "코드",
        CodeOnly: "코드만",
        CodeWithSystem: "코드(system 포함)",
        ComponentValue: "구성 요소 값",
        ComponentsCommaPlaceholder: "구성 요소(쉼표로 구분)",
        Composite: "Composite",
        CompositeCsvHint: "쉼표로 구분된 구성 요소가 두 개 이상이어야 합니다. FHIR composite 검색에서는 $로 연결됩니다.",
        CompositeCsvPlaceholder: "component1, component2, …",
        CompositeLocalBlocks: "로컬 구성 블록 사용(metadata가 없을 때 매개변수 이름으로 형식 추정). 블록마다 하나의 구성 요소이며 초안에 추가할 때 $로 연결.",
        CompositeMetadataFromServer: "서버 SearchParameter.component에서 로드됨(TD-1).",
        CompositeParameters: "복합 매개변수",
        Connect: "연결",
        ContactNameLine: "담당: Fan Shih-Chan(范士展)",
        CopyrightLineFormat: "© {0} 산업기술연구원(ITRI). 무단 전재 금지.",
        Copy: "복사",
        CopyTokenUrl: "token URL 복사",
        Date: "Date",
        DecimalNumber: "소수",
        Detected: "감지",
        EditorUnsupported: "이 매개변수 형식에는 형식화 편집기가 없습니다. 초안 줄 또는 원시 FHIR 구문을 사용하세요.",
        ElementsSortSection: "_elements／_sort",
        ElementsList: "Elements 목록",
        EmitEveryListedPath: "나열된 모든 경로보내기",
        ExecuteQuery: "쿼리 실행",
        FilterExpressionPlaceholder: "FHIR filter 식",
        FilterExpressions: "_filter 식",
        FhirBaseUrlPlaceholder: "FHIR base URL",
        FhirDeclaration: "FHIR 선언",
        FhirFilterPlaceholder: "FHIR filter 식",
        FooterAltItriLogo: "산업기술연구원(ITRI)",
        FullQueryUrlPlaceholder: "전체 쿼리 URL",
        JsonPlaceholder: "JSON",
        JwtClientCredentials: "JWT client_credentials",
        Language: "언어",
        LogicalId: "logical id",
        LogicalIdTypeSlash: "logical id(type/id)",
        MaxResultsInBundle: "Bundle 최대 항목 수",
        Modifier: "수정자",
        ModifierLabel: "수정자 레이블",
        ModifyingSectionTitle: "결과 수정 매개변수",
        NoDraftLines: "(초안 줄 없음)",
        Number: "Number",
        OpenAuthorizeUrl: "authorize URL 열기",
        OpenTokenUrl: "token URL 열기",
        OrCodedQuantity: "또는 coding 수량:",
        ParameterNamePlaceholder: "매개변수 이름",
        PaginationCount: "페이지 크기",
        PathPlaceholderChain: "경로(예: patient.name)",
        PrefixOption: "접두사",
        PrivateKeyPemPlaceholder: "기밀 클라이언트 PEM",
        Quantity: "Quantity",
        RefreshAccessToken: "access token 새로 고침",
        Reference: "Reference",
        RemoveSelected: "선택 항목 제거",
        ResetThisPage: "이 페이지 재설정",
        ResourceType: "리소스 유형",
        ResourceTypePh: "ResourceType",
        ResultControl: "결과 제어(_count, _offset, _total, _summary, _elements)",
        ResultElementsCsvPlaceholder: "쉼표로 구분된 요소 이름",
        ResultViewMessage: "메시지 보기",
        ResultViewTree: "트리 보기",
        Save: "저장…",
        ScopesPlaceholder: "Scopes",
        SelectedLabel: "선택:",
        SelectedNone: "(없음)",
        SmartLoginPkce: "SMART 로그인(브라우저 PKCE)",
        SmartOnFhir: "SMART on FHIR",
        SmartPatientContextFormat: "SMART patient 컨텍스트: {0}",
        SortList: "Sort 목록",
        SortPrefixMinus: "Sort 접두사 \"-\"",
        Special: "Special",
        SpecialValueHint: "값 형식은 이 SearchParameter에 따릅니다. 위 설명 또는 서버 문서를 참조하세요.",
        String: "String",
        SystemLabel: "system",
        TabAdvanced: "고급",
        TabInclude: "_include",
        TabModifyingResults: "결과 수정",
        TabRevInclude: "_revinclude",
        TabSearchParameters: "검색 매개변수",
        Token: "Token",
        TreeViewError: "트리 보기 오류(JSON이 너무 크거나 깊을 수 있음). 원문은「메시지 보기」를 사용하세요.",
        UnsetOption: "(미설정)",
        Uri: "Uri",
        UriValue: "URI 값",
        Value: "값",
        ValueNumberPlaceholder: "숫자",
        BearerTokenAvaloniaWatermark: "Bearer access token(선택, Execute query 시 Authorization 헤더로 전송)",
        Exit: "종료",
        FullQueryUrlBuiltBelow: "전체 쿼리 URL(아래에서 구성)",
        ResourceTypeAutocompleteWatermark: "리소스 유형 선택 또는 입력",
        SmartClientIdWatermark: "IdP에 등록된 client_id",
        SmartPrivateKeyPemWatermark: "기밀 클라이언트 RSA/EC 개인키 PEM(선택, appsettings의 ConfidentialPrivateKeyPem 사용 가능)",
        SmartScopesWatermark: "Scopes(예: launch/patient patient/*.read openid fhirUser offline_access)",
        TypedBuilderSection: "형식화 빌더",
        Version: "버전");
}
