using System;
using System.Text;
using FhirResourceCreator.Models;

namespace FhirResourceCreator.Generation;

/// <summary>
/// Emits mutable POCO DomainResource subclasses using System.Text.Json attributes (see FhirJsonSerializer).
/// </summary>
public static class PocoResourceGenerator
{
    public static string Generate(ResourceModel model, string rootNamespace)
    {
        var name = model.ResourceName ?? throw new InvalidOperationException("Resource name missing.");
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Fhir.TypeFramework.Bases;");
        sb.AppendLine("using Fhir.TypeFramework.DataTypes;");
        sb.AppendLine("using Fhir.TypeFramework.DataTypes.PrimitiveTypes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {name} : DomainResource");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ResourceTypeValue = \"{name}\";");
        sb.AppendLine();
        sb.AppendLine("    [JsonPropertyName(\"resourceType\")]");
        sb.AppendLine($"    public string ResourceTypeJson => ResourceTypeValue;");
        sb.AppendLine();

        var elements = model.Elements?.ToList() ?? new List<ElementRecord>();
        foreach (var el in elements.Where(e => e.ParentPath == name && !e.IsSkip))
        {
            AppendProperty(sb, el, elements, name, "    ", name);
        }

        foreach (var el in elements.Where(e => e.ParentPath == name && !e.IsSkip && EmitsAsNestedBackboneComponent(e, elements)))
        {
            AppendBackboneNested(sb, el, elements, "    ", name);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void AppendProperty(StringBuilder sb, ElementRecord el, List<ElementRecord> all, string parentPath, string indent, string resourceName)
    {
        if (EmitsAsNestedBackboneComponent(el, all))
        {
            var nested = NestedClassName(el, resourceName);
            var jsonName = el.OriginalElementName ?? el.FinalElementName!;
            sb.AppendLine($"{indent}[JsonPropertyName(\"{jsonName}\")]");
            var opt = el.IsMulti ? $"List<{nested}>?" : $"{nested}?";
            sb.AppendLine($"{indent}public {opt} {el.FinalElementName} {{ get; set; }}");
            sb.AppendLine();
            return;
        }

        if (el.IsChoice)
        {
            foreach (var code in el.ChoiceTypeCodes.Distinct(StringComparer.OrdinalIgnoreCase))
            {
                var clr = MapChoiceClrType(code);
                var jsonProp = ChoiceJsonPropertyName(el.OriginalElementName!, code);
                var propName = ChoicePropertyName(el.FinalElementName!, code);
                sb.AppendLine($"{indent}[JsonPropertyName(\"{jsonProp}\")]");
                sb.AppendLine($"{indent}public {clr}? {propName} {{ get; set; }}");
                sb.AppendLine();
            }
            return;
        }

        {
            var jsonName = el.OriginalElementName ?? el.FinalElementName!;
            sb.AppendLine($"{indent}[JsonPropertyName(\"{jsonName}\")]");
            sb.AppendLine($"{indent}public {ResolvePropertyType(el)} {el.FinalElementName} {{ get; set; }}");
            sb.AppendLine();
        }
    }

    static void AppendBackboneNested(StringBuilder sb, ElementRecord backboneHead, List<ElementRecord> all, string indent, string resourceName)
    {
        var path = backboneHead.ThisPath!;
        var className = NestedClassName(backboneHead, resourceName);
        var inner = indent + "    ";
        sb.AppendLine($"{indent}public partial class {className} : BackboneElement");
        sb.AppendLine($"{indent}{{");

        foreach (var el in all.Where(e => e.ParentPath == path && !e.IsSkip))
        {
            AppendProperty(sb, el, all, path, inner, resourceName);
        }

        foreach (var el in all.Where(e => e.ParentPath == path && !e.IsSkip && EmitsAsNestedBackboneComponent(e, all)))
        {
            AppendBackboneNested(sb, el, all, inner, resourceName);
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>
    /// FHIR snapshots often type repeating tuples as <c>Element</c> instead of <c>BackboneElement</c>; if child paths exist, emit a nested component type so JSON deserializes.
    /// </summary>
    static bool EmitsAsNestedBackboneComponent(ElementRecord el, List<ElementRecord> all)
    {
        if (el.IsBackboneElement)
            return true;

        if (!string.Equals(el.ClrTypeSimpleName, "Element", StringComparison.Ordinal))
            return false;

        if (string.IsNullOrEmpty(el.ThisPath))
            return false;

        return all.Exists(c => string.Equals(c.ParentPath, el.ThisPath, StringComparison.Ordinal));
    }

    /// <summary>
    /// Unique nested type per snapshot path (e.g. rest.searchParam vs rest.resource.searchParam; packaging.packaging recursion).
    /// </summary>
    static string NestedClassName(ElementRecord el, string resourceName)
    {
        var path = el.ThisPath;
        if (string.IsNullOrEmpty(path))
            return IdentifierUtility.ToPascalCase(el.OriginalElementName ?? "Nested") + "Component";

        var prefix = resourceName + ".";
        if (!path.StartsWith(prefix, StringComparison.Ordinal))
            return IdentifierUtility.ToPascalCase(el.OriginalElementName ?? "Nested") + "Component";

        var rel = path.Length > prefix.Length ? path[prefix.Length..] : "";
        if (string.IsNullOrEmpty(rel))
            return IdentifierUtility.ToPascalCase(el.OriginalElementName ?? "Nested") + "Component";

        var sb = new StringBuilder();
        foreach (var part in rel.Split('.'))
        {
            if (string.IsNullOrEmpty(part))
                continue;
            sb.Append(IdentifierUtility.ToPascalCase(part));
        }

        sb.Append("Component");
        return sb.ToString();
    }

    static string ResolvePropertyType(ElementRecord el)
    {
        if (el.IsPrimitive)
            return el.IsMulti ? $"List<{el.MappedPrimitiveClr}>?" : $"{el.MappedPrimitiveClr}?";

        var core = QualifyClrSimpleType(el.ClrTypeSimpleName);
        if (el.IsMulti)
            return $"List<{core}>?";
        return $"{core}?";
    }

    /// <summary>FHIR <c>Range</c> clashes with <see cref="System.Range"/> when implicit usings are on.</summary>
    static string QualifyClrSimpleType(string simpleName) =>
        simpleName switch
        {
            "Range" => "global::Fhir.TypeFramework.DataTypes.Range",
            _ => simpleName
        };

    static string MapChoiceClrType(string fhirCode)
    {
        var lower = fhirCode.ToLowerInvariant();
        if (PrimitiveTypeMapper.IsPrimitiveCode(lower))
            return PrimitiveTypeMapper.ToClrTypeName(lower);
        var pascal = IdentifierUtility.ToPascalCase(fhirCode);
        return QualifyClrSimpleType(pascal);
    }

    static string ChoiceJsonPropertyName(string elementName, string fhirCode)
    {
        var tail = PrimitiveTypeMapper.ToClrTypeName(fhirCode).Replace("Fhir", "");
        return char.ToLowerInvariant(elementName[0]) + elementName[1..] + tail;
    }

    static string ChoicePropertyName(string baseName, string fhirCode)
    {
        var tail = PrimitiveTypeMapper.ToClrTypeName(fhirCode).Replace("Fhir", "");
        return baseName + tail;
    }
}
